server:
    port: ":8888"
database:
    master: "root:@tcp(localhost:3306)/test"
api:
    mp: "https://api.docnet.id/CHCMasterProduk"
    outlet: "https://api.docnet.id/CHCMasterH/MasterOutlet/"
    do: "http://34.107.201.130/CHCDO/DO"