server:
    port: ":8888"
database:
    master: "spetnaz:sp3tn4z2019@tcp(34.87.44.167:3306)/TN-In?parseTime=true"
api:
    mp: "https://api.docnet.id/CHCMasterProduk"
    outlet: "https://api.docnet.id/CHCMasterH/MasterOutlet/"
